---
- name: docker build and push
  hosts: local
  become: true
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Build Docker Image
      ansible.builtin.command: docker build -t petstore .
      args:
        chdir: /var/lib/jenkins/workspace/petstore
    - name: Tag Image
      ansible.builtin.command: docker tag petstore:latest merajaprasd/petstore:latest
    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: merajaprasd
        password: dckr_pat_SHPHNQaXuhbA6JK5C6yD2VIY6tM
    - name: Push Image
      ansible.builtin.command: docker push merajaprasd/petstore:latest
    - name: Run Container
      ansible.builtin.command: docker run -d --name pet1 -p 8081:8080 merajaprasd/petstore:latest
