---
- name: Deploy Kubernetes Application
  hosts: k8s              # Replace with your target Kubernetes master host or group
  gather_facts: yes
  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/petstore/deployment.yaml  # Assuming Jenkins workspace variable
        dest: /root
      become: yes
      become_user: root
      
    - name: Apply Deployment
      ansible.builtin.command: kubectl apply -f /root/deployment.yaml
